### ISSUE TITLE
Redirect after autologin

### ISSUE THREAD

**Issue by wachalala** [MrApplejuice/wp-autologin-links#16]
Hello,

Is it possible to redirect the user after he autologged in ?

Thank you for that plugin :)

**Comment by MrApplejuice** [comment]
I know that this is open since a long time, but I have found some time to work on the plugin again atm.

In principle this is supported by encoding the autologin_code directly intop the URL: 

https://myside.com/some/link/to/page.html?autologin_code=abcdef123456

There is a handy-dandy admin-bar dropdown to assist you in the creation of these links:

![grafik](https://user-images.githubusercontent.com/542105/76907012-7e88ab80-68a5-11ea-922e-5d88173c2044.png)

Hope that helps!

If you want a proper redirect, I advise you to use another plugin that allows you to trigger a redirect once a user visits a certain page of yours.
