### ISSUE TITLE
After login redirection is done to www.domain.com/shop-base-url

### ISSUE THREAD

**Issue by tobbecokta** [MrApplejuice/wp-autologin-links#19]
Hi,

I am running a WP Multisite installation and are having issues with redirection after users have logged in with the autologin url.

When a user is going to this url https://domain.com/specific-url/?autologin_code=4ZTeB2Aze1YF4eJV281XkTXIoHtDqvRo he is automatically logged in and redirected to https;//domain./shop-base-url. This is wrong, the user should of course be redirected to  https://domain.com/specific-url/.

For your info:
This problem started occuring when I migrated several single installation sites into 1 WP Multisite.

Running WP Multisite version 5.3.2
Running Autologin plugin version 1.11.0

**Comment by MrApplejuice** [comment]
Hey! thanks for the bug report. I feared that the day would come where somebody would try out the plugin on a multisite setup. To be frank, I never properly tested it to this date. So at least it is good to hear that it does not break immediately. It should also be quite safe since it should only give you access to the controls as a site-admin - I hope at least.

I am collecting tickets right now for another minor update to the plugin. I think this will not make the cut for a minor update though since I need a multisite test setup first. I case you find and fix the issue, I can merge a PR earlier but until further notice I need to postpone this until the next update.

**Comment by tobbecokta** [comment]
Hey MrApplejuice,

It would be great to have this bug fixed, but unfortunently I do not have the competence to do it. Will you provide an updated version or is it possible to hire you to provide a fix?

**Comment by MrApplejuice** [comment]
Hello Tobias,

Thanks for reaching out. I have not had time to look into this issue yet. If you are interested in hiring me to fix it we can maybe arrange something via fiverr or a similar website. If that is an option for you, feel free to grab my email from my website https://www.craftware.info/owner/ to get in touch (I am not posting the address here to avoid receiving spam). 

Regards,
  Paul K.

**Comment by MrApplejuice** [comment]
Hello Tobias,

First of all: I received your email. Today, I did some initial research to see if I understand what this issue is about. But actually I cannot reproduce the issue at hand. I created a multisite installation with three sites:

![grafik](https://user-images.githubusercontent.com/542105/79639422-fc352500-818b-11ea-804d-3b63c099b2da.png)

* test lives on `http://localhost` (default)
* number2 lives on `http://localhost/number2`
* number3 lives on `http://localhost/number3`

I created a user called `mr22` who is subscriber to thw main website test and "number2". Now, admittedly the plugin has some odd behaviors since any site-administrator can reset login links on user accounts for their website, but other than that, everything seems to work:

* `http://localhost/number2/?autologin_code=r4ruVWgP74J6g3dauL6qGvQhpH4UYuEA` logs me in as `mr22` correctly redirects to the main-page of number2.
* `http://localhost/number2/archives/5?autologin_code=r4ruVWgP74J6g3dauL6qGvQhpH4UYuEA`  logs me in as `mr22` correctly redirects to a post I made for the website.
* `http://localhost/number2/wp-admin/import.php?autologin_code=r4ruVWgP74J6g3dauL6qGvQhpH4UYuEA` logs me in as `mr22` and brings me to the internal Tools/Import wp-admin page. 
* `http://localhost/nonexistent?autologin_code=r4ruVWgP74J6g3dauL6qGvQhpH4UYuEA` logs me in as `mr22` and brings me to a non existent page on the default website `test`.

I am never redirected to anything that is else. So since I cannot reproduce the error, I cannot really do anything about it.

----------------------

There must be a missing puzzle piece. You mention `http://domain/shop-base-url` - did you manually configure "shop-base-url" somewhere manually? Is your site using some DNS trickery to implement subdomains via redirects? Or redirects in general?

For general tips: maybe have another look at your `wp-config.php` and `.htaccess` file and verify that it is correctly setup according to the configuration shown in the Network Setup menu:

(here the one for my test setup)
![grafik](https://user-images.githubusercontent.com/542105/79642409-8cc83100-819d-11ea-81d6-665c7deeb4b1.png)

**Comment by tobbecokta** [comment]
Hi,

This issue is caused because of the plugin Wholesale Lead Capture from www.wholesalesuiteplugin.com. I have contacted their support team to get it fixed.

Thank you for taking the time to look into this.

**Comment by tobbecokta** [comment]
If anyone else have the same problem in the future with compability issues with the Wholesale Lead Capture plugin, here is a solution:

```
add_action( 'init' , function() {
    global $wc_wholesale_lead_capture;
    remove_action( 'wp_login' , array( $wc_wholesale_lead_capture->_wwlc_user_account, 'wwlc_multisite_redirect_after_login' ) , 10 , 2);
},5);
```

It'll disable the login redirection in a multisite environment. Your autologin link should work now.

**Comment by MrApplejuice** [comment]
Btw: Good to hear that you found a solution in the end - Good luck with your site and take care!
